name: Publish Package

on:
    push:
        branches:
            main

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: Release
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2

            - name: Set node version to 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://registry.npmjs.org/
                  cache: "pnpm"

            - name: Install deps
              run: pnpm i

            - name: Compiler
              run:  pnpm compiler

            - name: Build
              run: pnpm build

            - name: Publish All Packages
              run: pnpm -r run pub
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

