name: Publish Package

on:
    push:
        branches:
            main

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: Release
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Install deps
              run: pnpm i --no-frozen-lockfile --shamefully-hoist

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Clean
              run: pnpm clean

            - name: Compiler
              run:  pnpm compiler

            - name: Build
              run: pnpm build

            - name: Publish All Packages
              run: pnpm -r run pub
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

